# .rubocop.yml
inherit_gem:
  rubocop-github:
  - config/default.yml # generic Ruby rules and cops
  - config/rails.yml # Rails-specific rules and cops


Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: false
